# Generated by Django 3.2.12 on 2022-05-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
