# Generated by Django 3.2.12 on 2022-05-26 10:23

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220524_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_steps_is_html',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=recipes.models.get_default_category, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category'),
        ),
    ]
